### ISSUE TITLE
Player.getEyeLocation not implemented

### ISSUE THREAD

**Issue by OverTook** [rutgerkok/Pokkit#10]
Exception in thread "Thread-12" java.lang.UnsupportedOperationException: This method is not supported yet by Pokkit 0.2-SNAPSHOT
        at nl.rutgerkok.pokkit.Pokkit.unsupported(Pokkit.java:65)
        at nl.rutgerkok.pokkit.player.PokkitPlayer.getEyeLocation(PokkitPlayer.java:433)
        at com.xxmicloxx.NoteBlockAPI.RadioSongPlayer.playTick(RadioSongPlayer.java:25)
        at com.xxmicloxx.NoteBlockAPI.SongPlayer$1.run(SongPlayer.java:111)
        at java.lang.Thread.run(Unknown Source)

when i play Music on my Server, this error happened.

(different plugin that is kind of Music also crashed.)

sorry for my english, and thanks~ :D

**Comment by rutgerkok** [comment]
Thanks, I'll leave this report open in case anyone is interested in fixing this.

**Comment by OverTook** [comment]
@rutgerkok thx!

**Comment by OverTook** [comment]
@rutgerkok but, i don't know how to fix it in github.

**Comment by rutgerkok** [comment]
I don't expect you to fix it. I'm just not interested in fixing this bug myself. See [this page](https://github.com/rutgerkok/Pokkit/blob/master/README.md) for an explanation why.

**Comment by OverTook** [comment]
okay, thanks for replying

**Comment by rutgerkok** [comment]
From the [README](https://github.com/rutgerkok/Pokkit/blob/master/README.md):

> Still, I will leave open all valid bug reports, so that anyone interested in improving Pokkit can have a look.

So I'll reopen this issue.

**Comment by MrPowerGamerBR** [comment]
Will implement this as soon as possible, won't be easy since Nukkit doesn't have an API to get the eye location, so I will need to scavenge thru CraftBukkit's code to see how it is calculated.

(Player is easy, just add 1.62 to the getLocation(), but there are other mobs...)
