### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by coolkidsrule101** [rutgerkok/Pokkit#107]
01:05:46 [CRITICAL] Could not pass event 'cn.nukkit.event.player.PlayerInteractEvent' to 'Pokkit v0.6-SNAPSHOT': null on nl.rutgerkok.pokkit.pluginservice.PlayerInteractEvents
01:05:46 [ALERT] cn.nukkit.utils.EventException
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34)
	at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56)
	at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:542)
	at cn.nukkit.block.BlockPressurePlateBase.onEntityCollide(BlockPressurePlateBase.java:130)
	at cn.nukkit.Player.checkBlockCollision(Player.java:1370)
	at cn.nukkit.entity.Entity.entityBaseTick(Entity.java:1105)
	at cn.nukkit.entity.EntityLiving.entityBaseTick(EntityLiving.java:201)
	at cn.nukkit.Player.onUpdate(Player.java:1635)
	at cn.nukkit.level.Level.doTick(Level.java:749)
	at cn.nukkit.Server.checkTickUpdates(Server.java:999)
	at cn.nukkit.Server.tick(Server.java:1085)
	at cn.nukkit.Server.tickProcessor(Server.java:848)
	at cn.nukkit.Server.start(Server.java:825)
	at cn.nukkit.Server.<init>(Server.java:508)
	at cn.nukkit.Nukkit.main(Nukkit.java:99)
Caused by: java.lang.NullPointerException
	at nl.rutgerkok.pokkit.world.PokkitBlockFace.toBukkit(PokkitBlockFace.java:9)
	at nl.rutgerkok.pokkit.pluginservice.PlayerInteractEvents.onPlayerInteract(PlayerInteractEvents.java:57)
	at sun.reflect.GeneratedMethodAccessor30.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29)
	... 14 more

**Comment by Smartjer123** [comment]
I doubt your going to get help because I posted something on Feb 10 and still no response

**Comment by rutgerkok** [comment]
Exactly. From the main page:

> ## Bug reports
>
> In general, I will only fix a bug for you if happens to also affect me. Pokkit is a personal project that I uploaded in the hope that it will be useful to others, but I'm not willing to spend the time to create a complete, bug-free implementation of the Spigot API. See my reasoning in the introduction.
>
> Still, I will leave open all valid bug reports, so that anyone interested in improving Pokkit can have a look.
