### ISSUE TITLE
Dynmap Error

### ISSUE THREAD

**Issue by min20120907** [rutgerkok/Pokkit#108]
when I use dynmap load on the nukkit server, it doesn't work any single time...

**Comment by min20120907** [comment]
[CRITICAL] 於 dynmap 執行指令 「dynmap」 時，出現了未被處理的錯誤： java.lang.NullPointerException
	at org.dynmap.bukkit.DynmapPlugin.onCommand(DynmapPlugin.java:937)
	at nl.rutgerkok.pokkit.plugin.PokkitPlugin.onCommand(PokkitPlugin.java:281)
	at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33)
	at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:261)
	at cn.nukkit.Server.dispatchCommand(Server.java:694)
	at cn.nukkit.Player.handleDataPacket(Player.java:2672)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at cn.nukkit.network.Network.processPackets(Network.java:179)
	at cn.nukkit.network.Network.processBatch(Network.java:161)
	at cn.nukkit.Player.handleDataPacket(Player.java:2042)
	at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
	at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132)
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
	at cn.nukkit.network.Network.processInterfaces(Network.java:76)
	at cn.nukkit.Server.tick(Server.java:1071)
	at cn.nukkit.Server.tickProcessor(Server.java:848)
	at cn.nukkit.Server.start(Server.java:825)
	at cn.nukkit.Server.<init>(Server.java:514)
	at cn.nukkit.Nukkit.main(Nukkit.java:109)

10:13:49 [ALERT] java.lang.NullPointerException
	at org.dynmap.bukkit.DynmapPlugin.onCommand(DynmapPlugin.java:937)
	at nl.rutgerkok.pokkit.plugin.PokkitPlugin.onCommand(PokkitPlugin.java:281)
	at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33)
	at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:261)
	at cn.nukkit.Server.dispatchCommand(Server.java:694)
	at cn.nukkit.Player.handleDataPacket(Player.java:2672)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at cn.nukkit.network.Network.processPackets(Network.java:179)
	at cn.nukkit.network.Network.processBatch(Network.java:161)
	at cn.nukkit.Player.handleDataPacket(Player.java:2042)
	at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
	at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132)
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
	at cn.nukkit.network.Network.processInterfaces(Network.java:76)
	at cn.nukkit.Server.tick(Server.java:1071)
	at cn.nukkit.Server.tickProcessor(Server.java:848)
	at cn.nukkit.Server.start(Server.java:825)
	at cn.nukkit.Server.<init>(Server.java:514)

**Comment by WesleyVanNeck** [comment]
its dead so dont botter

**Comment by MothGirlMusic** [comment]
did dynmap actually ever work with this? i'm actually legitly curious.. because you'd think even with being able to run bukkit plugins, you'd assume it wouldn't work anyway since maps are saved differently and it needs to be able to read the region files nukkit doesn't keep.
