### ISSUE TITLE
Pokkit breaks (some) Nukkit plugins

### ISSUE THREAD

**Issue by MrPowerGamerBR** [rutgerkok/Pokkit#13]
```
16:53:23 [INFO] [Pokkit] Set PluginClassLoader as parallel capable
16:53:23 [DEBUG] Could not load plugin
org.bukkit.plugin.InvalidPluginException: main class `ru.nukkit.regions.RegionsPlugin' does not extend JavaPlugin
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:73)
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129)
        at nl.rutgerkok.pokkit.plugin.PokkitPluginLoader.loadPlugin(PokkitPluginLoader.java:92)
        at cn.nukkit.plugin.PluginManager.loadPlugin(PluginManager.java:96)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:278)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:133)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:125)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:121)
        at cn.nukkit.Server.<init>(Server.java:379)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)
Caused by: java.lang.ClassCastException: class ru.nukkit.regions.RegionsPlugin
        at java.lang.Class.asSubclass(Unknown Source)
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:71)
        ... 9 more

16:53:23 [CRITICAL] NÒo foi possÝvel carregar o plugin 'Regions'
16:53:23 [DEBUG] Could not load plugin
org.bukkit.plugin.InvalidPluginException: main class `com.mrpowergamerbr.sparklychat.SparklyChat' does not extend JavaPlugin
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:73)
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129)
        at nl.rutgerkok.pokkit.plugin.PokkitPluginLoader.loadPlugin(PokkitPluginLoader.java:92)
        at cn.nukkit.plugin.PluginManager.loadPlugin(PluginManager.java:96)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:278)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:133)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:125)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:121)
        at cn.nukkit.Server.<init>(Server.java:379)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)
Caused by: java.lang.ClassCastException: class com.mrpowergamerbr.sparklychat.SparklyChat
        at java.lang.Class.asSubclass(Unknown Source)
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:71)
        ... 9 more

16:53:23 [CRITICAL] NÒo foi possÝvel carregar o plugin 'SparklyChat'
16:53:23 [DEBUG] Could not load plugin
org.bukkit.plugin.InvalidPluginException: main class `com.mrpowergamerbr.sparklyelevadores.SparklyElevadores' does not extend JavaPlugin
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:73)
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129)
        at nl.rutgerkok.pokkit.plugin.PokkitPluginLoader.loadPlugin(PokkitPluginLoader.java:92)
        at cn.nukkit.plugin.PluginManager.loadPlugin(PluginManager.java:96)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:278)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:133)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:125)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:121)
        at cn.nukkit.Server.<init>(Server.java:379)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)
Caused by: java.lang.ClassCastException: class com.mrpowergamerbr.sparklyelevadores.SparklyElevadores
        at java.lang.Class.asSubclass(Unknown Source)
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:71)
        ... 9 more

16:53:23 [CRITICAL] NÒo foi possÝvel carregar o plugin 'SparklyElevadores'
16:53:23 [DEBUG] Could not load plugin
org.bukkit.plugin.InvalidPluginException: main class `com.mrpowergamerbr.sparklypvptweaks.SparklyPvPTweaks' does not extend JavaPlugin
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:73)
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129)
        at nl.rutgerkok.pokkit.plugin.PokkitPluginLoader.loadPlugin(PokkitPluginLoader.java:92)
        at cn.nukkit.plugin.PluginManager.loadPlugin(PluginManager.java:96)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:278)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:133)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:125)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:121)
        at cn.nukkit.Server.<init>(Server.java:379)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)
Caused by: java.lang.ClassCastException: class com.mrpowergamerbr.sparklypvptweaks.SparklyPvPTweaks
        at java.lang.Class.asSubclass(Unknown Source)
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:71)
        ... 9 more

16:53:23 [CRITICAL] NÒo foi possÝvel carregar o plugin 'SparklyPvPTweaks'
16:53:23 [DEBUG] Could not load plugin
org.bukkit.plugin.InvalidPluginException: main class `ru.nukkit.multipass.MultipassPlugin' does not extend JavaPlugin
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:73)
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129)
        at nl.rutgerkok.pokkit.plugin.PokkitPluginLoader.loadPlugin(PokkitPluginLoader.java:92)
        at cn.nukkit.plugin.PluginManager.loadPlugin(PluginManager.java:96)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:294)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:133)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:125)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:121)
        at cn.nukkit.Server.<init>(Server.java:379)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)
Caused by: java.lang.ClassCastException: class ru.nukkit.multipass.MultipassPlugin
        at java.lang.Class.asSubclass(Unknown Source)
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:71)
        ... 9 more

16:53:23 [CRITICAL] NÒo foi possÝvel carregar o plugin 'Multipass'
```
And, of course, all of those plugins are inside the Nukkit's plugin directory (NOT Pokkit's plugin directory) but Pokkit tries to load them and fails.

**Comment by rutgerkok** [comment]
Based on the plugin names, I guess everything that comes after "Pokkit" alphabetically cannot be loaded. I guess I made a mistake when I changed Pokkit's plugin loader: all Nukkit plugins loaded after Pokkit is loaded are treated as if they were Bukkit plugins.

**Comment by rutgerkok** [comment]
I made some changes that should hopefully fix this bug. You can download a test file here:

https://dl.dropboxusercontent.com/u/23288978/Pokkit.jar

**Comment by MrPowerGamerBR** [comment]
@rutgerkok fixed!
