### ISSUE TITLE
Support AntiHacks plugin

### ISSUE THREAD

**Issue by NycuRO** [rutgerkok/Pokkit#29]
Plugin issue , not found EntityPlayer.. 👍  You can add @MrPowerGamerBR or @rutgerkok or @Langsdorf or @ZINGDING 
23:36:18 [INFO] [Pokkit] [MineSecure] Enabling MineSecure v4.1
> java.lang.ClassNotFoundException: net.minecraft.server.v1_99_R9.EntityPlayer
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at me.gervobis.netty.Reflection.getClass(h:199)
        at me.gervobis.netty.PacketInjector.<init>(e:210)
        at me.gervobis.antihack.Main.onEnable(x:18)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
        at nl.rutgerkok.pokkit.plugin.PokkitPluginLoader.enablePlugin(PokkitPluginLoader.java:69)
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:456)
        at cn.nukkit.Server.enablePlugin(Server.java:618)
        at cn.nukkit.Server.enablePlugins(Server.java:607)
        at cn.nukkit.Server.<init>(Server.java:454)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)
java.lang.NullPointerException
        at me.gervobis.netty.Reflection.getField(h:116)
        at me.gervobis.netty.PacketInjector.<init>(e:210)
        at me.gervobis.antihack.Main.onEnable(x:18)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
        at nl.rutgerkok.pokkit.plugin.PokkitPluginLoader.enablePlugin(PokkitPluginLoader.java:69)
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:456)
        at cn.nukkit.Server.enablePlugin(Server.java:618)
        at cn.nukkit.Server.enablePlugins(Server.java:607)
        at cn.nukkit.Server.<init>(Server.java:454)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)
23:36:19 [INFO] Supported Hacks: Aimbot, BowAimbot, KillAura, Fly (Beta), NoFall, NoSwing, FastEat, FastHeal, InvWalk, Spam, WaterWalk (Jesus), Glide, AutoRespawn, CreativeNuker, FastBow, AutoClicker, BedFucker, Phase, FastLadder, SpeedHack (WaterSpeed/FlySpeed/Speed), AntiKnockBack, Reach
23:36:19 [INFO] ===========[MineSecure] Updater===========
23:36:19 [INFO] Plugin is Up-To-Date: v4.1
23:36:19 [INFO] ===========[MineSecure] Updater===========
23:36:19 [INFO] [Pokkit] [TrailGUI] Enabling TrailGUI v5.0.1-b62-SNAPSHOT

PLUGIN : https://www.spigotmc.org/resources/minesecure-antihacksystem-aimbot-killaura-bungeecord-support.11996/

**Comment by MrPowerGamerBR** [comment]
I ALREADY SAID BEFORE THAT POKKIT **WON'T** SUPPORT PLUGINS THAT USES NON-BUKKIT API CLASSES.

**Comment by NycuRO** [comment]
@MrPowerGamerBR Yes but is EntityPlayer man.. You cannot add costum folder? :/

**Comment by NycuRO** [comment]
Pokkit = compatible plugins PC ( Like Bukkit and Spigot ). Why you not create for more plugins ?

**Comment by MrPowerGamerBR** [comment]
> net.minecraft.server

I won't waste my time implementing methods that change every time Minecraft updates, if you want to support plugins that uses NMS, then do it yourself, also.

> Nukkit plugin that is able to load Bukkit plugins

Bukkit plugins, not CraftBukkit plugins.

**Comment by NycuRO** [comment]
@MrPowerGamerBR This uses Bukkit class: https://www.spigotmc.org/resources/wolf-anticheat-1-7-1-8.18614/

> Exception in thread "Nukkit Asynchronous Task Handler #1" java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
        at be.seveningful.wolf.Metrics.postPlugin(Metrics.java:335)
        at be.seveningful.wolf.Metrics.access$400(Metrics.java:57)
        at be.seveningful.wolf.Metrics$1.run(Metrics.java:223)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by MrPowerGamerBR** [comment]
@NycuRO outdated plugin.

**Comment by NycuRO** [comment]
@MrPowerGamerBR What? You can explain me is " outdated " ?

**Comment by MrPowerGamerBR** [comment]
@NycuRO http://www.thefreedictionary.com/outdated

**Comment by NycuRO** [comment]
Ok thanks, @MrPowerGamerBR , but you know one plugin " AntiCheats" for Genisys or Nukkit?

**Comment by MrPowerGamerBR** [comment]
@NycuRO I doubt using a PC AntiCheat plugin would be good for a MCPE server.
