### ISSUE TITLE
Armour support or idk

### ISSUE THREAD

**Issue by NycuRO** [rutgerkok/Pokkit#30]
Error: @MrPowerGamerBR 
Plugin: https://dev.bukkit.org/bukkit-plugins/kitplugin/

20:32:18 [CRITICAL] Unhandled exception executing command 'kit start' in kit: java.lang.ClassCastException: nl.rutgerkok.pokkit.world.item.PokkitItemMeta cannot be cast to org.bukkit.inventory.meta.LeatherArmorMeta
        at com.recon.KitPlugin.Handler.KitHandler.colorizeArmor(KitHandler.java:332)
        at com.recon.KitPlugin.Handler.KitHandler.giveKit(KitHandler.java:155)
        at com.recon.KitPlugin.Handler.CommandHandler.onCommand(CommandHandler.java:90)
        at nl.rutgerkok.pokkit.plugin.PokkitPlugin.onCommand(PokkitPlugin.java:279)
        at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:225)
        at cn.nukkit.Server.dispatchCommand(Server.java:630)
        at cn.nukkit.Player.handleDataPacket(Player.java:2663)
        at cn.nukkit.network.Network.processPackets(Network.java:193)
        at cn.nukkit.network.Network.processBatch(Network.java:164)
        at cn.nukkit.Player.handleDataPacket(Player.java:1750)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:154)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:63)
        at cn.nukkit.network.Network.processInterfaces(Network.java:75)
        at cn.nukkit.Server.tick(Server.java:989)
        at cn.nukkit.Server.tickProcessor(Server.java:786)
        at cn.nukkit.Server.start(Server.java:765)
        at cn.nukkit.Server.<init>(Server.java:456)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)

**Comment by Langsdorf** [comment]
Problem solved :+1: !
Pull request created.

P.S:
**Minecraft PE doesn’t support colors in leather armor...**

**Comment by ZINGDING** [comment]
@Langsdorf 
Thanks! :)

**Comment by NycuRO** [comment]
@Langsdorf Nukkit not support. MCPE have support.

**Comment by Langsdorf** [comment]
@NycuRO Yeah... Sorry! :P
