### ISSUE TITLE
NullPointerException in EnchantmentWrapper.getStartLevel

### ISSUE THREAD

**Issue by NycuRO** [rutgerkok/Pokkit#31]
Plugin: https://www.spigotmc.org/resources/kit.24164/

Error: 20:52:05 [ALERT] java.lang.NullPointerException
        at org.bukkit.enchantments.EnchantmentWrapper.getStartLevel(EnchantmentWrapper.java:29)
        at org.bukkit.inventory.ItemStack.addEnchantment(ItemStack.java:437)
        at fr.werter.kit.item(kit.java:91)
        at fr.werter.kit.onCommand(kit.java:156)
        at nl.rutgerkok.pokkit.plugin.PokkitPlugin.onCommand(PokkitPlugin.java:279)
        at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:225)
        at cn.nukkit.Server.dispatchCommand(Server.java:630)
        at cn.nukkit.Player.handleDataPacket(Player.java:2663)
        at cn.nukkit.network.Network.processPackets(Network.java:193)
        at cn.nukkit.network.Network.processBatch(Network.java:164)
        at cn.nukkit.Player.handleDataPacket(Player.java:1750)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:154)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:63)
        at cn.nukkit.network.Network.processInterfaces(Network.java:75)
        at cn.nukkit.Server.tick(Server.java:989)
        at cn.nukkit.Server.tickProcessor(Server.java:786)
        at cn.nukkit.Server.start(Server.java:765)
        at cn.nukkit.Server.<init>(Server.java:456)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)

**Comment by NycuRO** [comment]
@MrPowerGamerBR @rutgerkok @Langsdorf @ZINGDING

**Comment by leonardosnt** [comment]
> "Do not expect that Pokkit allows you to run a random Spigot plugin on Nukkit. Pokkit is **still very incomplete**, so only a handful of plugins will work..."

**Comment by MrPowerGamerBR** [comment]
> In general, I will only fix a bug for you if happens to also affect me. Pokkit is a personal project that I uploaded in the hope that it will be useful to others, but I'm not willing to spend the time to create a complete, bug-free implementation of the Spigot API. See my reasoning in the introduction.

Also, quoting me won't automagically make me impelment that, I'm not messing around with Nukkit (and Pokkit) until 0.16.0 is released and Nukkit is updated to 0.16.0.

**Comment by NycuRO** [comment]
Ok ,sorry. I'm created with one answer . thx

**Comment by rutgerkok** [comment]
I'm reopening this issue. Although I personally have no interest in fixing this right now, it is still a valid bug report, so it can be left open.

**Comment by NycuRO** [comment]
Ok @rutgerkok :)
