### ISSUE TITLE
ClearLagg error

### ISSUE THREAD

**Issue by NycuRO** [rutgerkok/Pokkit#33]
ClearLagg plugin.

Error : 15:36:39 [ALERT] java.lang.UnsupportedOperationException: This method is not supported yet by Pokkit 0.5-SNAPSHOT
        at nl.rutgerkok.pokkit.Pokkit.unsupported(Pokkit.java:81)
        at nl.rutgerkok.pokkit.world.PokkitChunk.getTileEntities(PokkitChunk.java:71)
        at me.minebuilders.clearlag.commands.CheckCmd.run(CheckCmd.java:61)
        at me.minebuilders.clearlag.modules.CommandModule.run(CommandModule.java:40)
        at me.minebuilders.clearlag.modules.CommandModule.processCmd(CommandModule.java:33)
        at me.minebuilders.clearlag.CommandListener.onCommand(CommandListener.java:40)
        at nl.rutgerkok.pokkit.plugin.PokkitPlugin.onCommand(PokkitPlugin.java:281)
        at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:225)
        at cn.nukkit.Server.dispatchCommand(Server.java:630)
        at cn.nukkit.Player.handleDataPacket(Player.java:2663)
        at cn.nukkit.network.Network.processPackets(Network.java:193)
        at cn.nukkit.network.Network.processBatch(Network.java:164)
        at cn.nukkit.Player.handleDataPacket(Player.java:1750)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:154)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:63)
        at cn.nukkit.network.Network.processInterfaces(Network.java:75)
        at cn.nukkit.Server.tick(Server.java:989)
        at cn.nukkit.Server.tickProcessor(Server.java:786)
        at cn.nukkit.Server.start(Server.java:765)
        at cn.nukkit.Server.<init>(Server.java:456)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)

**Comment by NycuRO** [comment]
/lagg halt : 

15:39:46 [ALERT] java.lang.UnsupportedOperationException: This method is not supported yet by Pokkit 0.5-SNAPSHOT
        at nl.rutgerkok.pokkit.Pokkit.unsupported(Pokkit.java:81)
        at nl.rutgerkok.pokkit.world.PokkitWorld.getAmbientSpawnLimit(PokkitWorld.java:177)
        at me.minebuilders.clearlag.tasks.HaltTask.setEnabled(HaltTask.java:48)
        at me.minebuilders.clearlag.commands.HaltCmd.run(HaltCmd.java:23)
        at me.minebuilders.clearlag.modules.CommandModule.run(CommandModule.java:40)
        at me.minebuilders.clearlag.modules.CommandModule.processCmd(CommandModule.java:33)
        at me.minebuilders.clearlag.CommandListener.onCommand(CommandListener.java:40)
        at nl.rutgerkok.pokkit.plugin.PokkitPlugin.onCommand(PokkitPlugin.java:281)
        at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:225)
        at cn.nukkit.Server.dispatchCommand(Server.java:630)
        at cn.nukkit.Player.handleDataPacket(Player.java:2663)
        at cn.nukkit.network.Network.processPackets(Network.java:193)
        at cn.nukkit.network.Network.processBatch(Network.java:164)
        at cn.nukkit.Player.handleDataPacket(Player.java:1750)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:154)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:63)
        at cn.nukkit.network.Network.processInterfaces(Network.java:75)
        at cn.nukkit.Server.tick(Server.java:989)
        at cn.nukkit.Server.tickProcessor(Server.java:786)
        at cn.nukkit.Server.start(Server.java:765)
        at cn.nukkit.Server.<init>(Server.java:456)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)

**Comment by rutgerkok** [comment]
Noted, thanks.

(As stated in the README, bugs like these will only be fixed if anyone is interested in fixing them.)

**Comment by NycuRO** [comment]
Ok :) I want to report all bugs is possible fixed for pokkit make very grateful :)
