### ISSUE TITLE
BuyHead: World.spawnEntity

### ISSUE THREAD

**Issue by NycuRO** [rutgerkok/Pokkit#35]
Plugin: https://www.spigotmc.org/resources/buyhead.14660/update?update=55263

Error: If you create /buyh newshop <name> get this error:

16:54:18 [CRITICAL] Unhandled exception executing command 'buyh newshop test' in buyhead: java.lang.UnsupportedOperationException: This method is not supported yet by Pokkit 0.5-SNAPSHOT
        at nl.rutgerkok.pokkit.Pokkit.unsupported(Pokkit.java:81)
        at nl.rutgerkok.pokkit.world.PokkitWorld.spawnEntity(PokkitWorld.java:756)
        at me.poutineqc.buyhead.shop.Shop.<init>(Shop.java:56)
        at me.poutineqc.buyhead.commands.Buyh.onCommand(Buyh.java:155)
        at nl.rutgerkok.pokkit.plugin.PokkitPlugin.onCommand(PokkitPlugin.java:281)
        at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:225)
        at cn.nukkit.Server.dispatchCommand(Server.java:630)
        at cn.nukkit.Player.handleDataPacket(Player.java:2663)
        at cn.nukkit.network.Network.processPackets(Network.java:193)
        at cn.nukkit.network.Network.processBatch(Network.java:164)
        at cn.nukkit.Player.handleDataPacket(Player.java:1750)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:154)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:63)
        at cn.nukkit.network.Network.processInterfaces(Network.java:75)
        at cn.nukkit.Server.tick(Server.java:989)
        at cn.nukkit.Server.tickProcessor(Server.java:786)
        at cn.nukkit.Server.start(Server.java:765)
        at cn.nukkit.Server.<init>(Server.java:456)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)

16:54:18 [ALERT] java.lang.UnsupportedOperationException: This method is not supported yet by Pokkit 0.5-SNAPSHOT
        at nl.rutgerkok.pokkit.Pokkit.unsupported(Pokkit.java:81)
        at nl.rutgerkok.pokkit.world.PokkitWorld.spawnEntity(PokkitWorld.java:756)
        at me.poutineqc.buyhead.shop.Shop.<init>(Shop.java:56)
        at me.poutineqc.buyhead.commands.Buyh.onCommand(Buyh.java:155)
        at nl.rutgerkok.pokkit.plugin.PokkitPlugin.onCommand(PokkitPlugin.java:281)
        at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:225)
        at cn.nukkit.Server.dispatchCommand(Server.java:630)
        at cn.nukkit.Player.handleDataPacket(Player.java:2663)
        at cn.nukkit.network.Network.processPackets(Network.java:193)
        at cn.nukkit.network.Network.processBatch(Network.java:164)
        at cn.nukkit.Player.handleDataPacket(Player.java:1750)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:154)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:63)
        at cn.nukkit.network.Network.processInterfaces(Network.java:75)
        at cn.nukkit.Server.tick(Server.java:989)
        at cn.nukkit.Server.tickProcessor(Server.java:786)
        at cn.nukkit.Server.start(Server.java:765)
        at cn.nukkit.Server.<init>(Server.java:456)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)

**Comment by Langsdorf** [comment]
Pull request created =)
