### ISSUE TITLE
Marriage Master: Player.chat

### ISSUE THREAD

**Issue by NycuRO** [rutgerkok/Pokkit#38]
Plugin: https://mods.curse.com/bukkit-plugins/minecraft/marriage-master
All functions work ,but not work /marry gift

Bug; 16:28:47 [ALERT] java.lang.UnsupportedOperationException: This method is not supported yet by Pokkit 0.5-SNAPSHOT
        at nl.rutgerkok.pokkit.Pokkit.unsupported(Pokkit.java:81)
        at nl.rutgerkok.pokkit.player.PokkitPlayer.chat(PokkitPlayer.java:264)
        at at.pcgamingfreaks.MarriageMaster.Bukkit.Commands.Priest.MarryPlayer(Priest.java:381)
        at at.pcgamingfreaks.MarriageMaster.Bukkit.Commands.Priest.Marry(Priest.java:154)
        at at.pcgamingfreaks.MarriageMaster.Bukkit.Listener.OnCommand.onCommand(OnCommand.java:846)
        at nl.rutgerkok.pokkit.plugin.PokkitPlugin.onCommand(PokkitPlugin.java:281)
        at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:225)
        at cn.nukkit.Server.dispatchCommand(Server.java:630)
        at cn.nukkit.Player.handleDataPacket(Player.java:2663)
        at cn.nukkit.network.Network.processPackets(Network.java:193)
        at cn.nukkit.network.Network.processBatch(Network.java:164)
        at cn.nukkit.Player.handleDataPacket(Player.java:1750)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:154)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:65)
        at cn.nukkit.network.Network.processInterfaces(Network.java:75)
        at cn.nukkit.Server.tick(Server.java:977)
        at cn.nukkit.Server.tickProcessor(Server.java:786)
        at cn.nukkit.Server.start(Server.java:765)
        at cn.nukkit.Server.<init>(Server.java:456)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)

**Comment by Langsdorf** [comment]
Pull request created =)
