### ISSUE TITLE
Pokkit not work

### ISSUE THREAD

**Issue by NycuRO** [rutgerkok/Pokkit#5]
Plugin not work. If i'm starting server,plugin get errors and is not loaded..

**Comment by NycuRO** [comment]
[ERROR] Could not load 'pokkit.jar' in folder 'C:\Users\user\Desktop\nukkit\plugins': java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.String
        at cn.nukkit.plugin.PluginDescription.loadMap(PluginDescription.java:202)
        at cn.nukkit.plugin.PluginDescription.<init>(PluginDescription.java:137)
        at cn.nukkit.plugin.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:94)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:169)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:133)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:125)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:121)
        at cn.nukkit.Server.<init>(Server.java:380)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)

22:47:56 [ALERT] java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.String
        at cn.nukkit.plugin.PluginDescription.loadMap(PluginDescription.java:202)
        at cn.nukkit.plugin.PluginDescription.<init>(PluginDescription.java:137)
        at cn.nukkit.plugin.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:94)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:169)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:133)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:125)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:121)
        at cn.nukkit.Server.<init>(Server.java:380)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)

@ZINGDING
