### ISSUE TITLE
/echest ,essentials not work

### ISSUE THREAD

**Issue by NycuRO** [rutgerkok/Pokkit#61]
Echest essentials not work.

I don't have error, say: That isn't supported in pokkit 0.5.

Please you can add support? @MrPowerGamerBR 

IS VERY IMPORTANT FEATURE :)

**Comment by artur9010** [comment]
Enderchests works in Nukkit?

**Comment by NycuRO** [comment]
Yes.

**Comment by NycuRO** [comment]
And /ecraft if is possible. Need registre Inventoryes :)

**Comment by NycuRO** [comment]
Error:

java.lang.UnsupportedOperationException: This method is not supported yet by Pokkit 0.5-SNAPSHOT
        at nl.rutgerkok.pokkit.Pokkit.unsupported(Pokkit.java:81)
        at nl.rutgerkok.pokkit.player.PokkitPlayer.closeInventory(PokkitPlayer.java:277)
        at com.earth2me.essentials.commands.Commandenderchest.run(Commandenderchest.java:26)
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:180)
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:526)
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:401)
        at nl.rutgerkok.pokkit.plugin.PokkitPlugin.onCommand(PokkitPlugin.java:281)
        at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:225)
        at cn.nukkit.Server.dispatchCommand(Server.java:644)
        at cn.nukkit.Player.handleDataPacket(Player.java:2947)
        at cn.nukkit.network.Network.processPackets(Network.java:185)
        at cn.nukkit.network.Network.processBatch(Network.java:156)
        at cn.nukkit.Player.handleDataPacket(Player.java:1906)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:155)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:64)
        at cn.nukkit.network.Network.processInterfaces(Network.java:76)
        at cn.nukkit.Server.tick(Server.java:997)
        at cn.nukkit.Server.tickProcessor(Server.java:800)
        at cn.nukkit.Server.start(Server.java:779)
        at cn.nukkit.Server.<init>(Server.java:464)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)
