### ISSUE TITLE
Timer? :o Essentials

### ISSUE THREAD

**Issue by NycuRO** [rutgerkok/Pokkit#63]
Bug on essentials, spam error:

23:49:32 [CRITICAL] Exception while invoking run
java.lang.NullPointerException
        at com.earth2me.essentials.EssentialsTimer.run(EssentialsTimer.java:99)
        at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99)
        at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:282)
        at cn.nukkit.Server.tick(Server.java:1005)
        at cn.nukkit.Server.tickProcessor(Server.java:800)
        at cn.nukkit.Server.start(Server.java:779)
        at cn.nukkit.Server.<init>(Server.java:464)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)

**Comment by MrPowerGamerBR** [comment]
As a reference:
```
if (user.getLastOnlineActivity() < currentTime && user.getLastOnlineActivity() > user.getLastLogout())
```
This line is throwing NPE with Pokkit
