### ISSUE TITLE
EventException bug, on WorldGuard

### ISSUE THREAD

**Issue by NycuRO** [rutgerkok/Pokkit#64]
22:09:28 [ERROR] [Pokkit] Could not pass event BlockBreakEvent to WorldGuard v6.1.3-SNAPSHOT;c904242
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at nl.rutgerkok.pokkit.plugin.BukkitEventManager.fireEvent(BukkitEventManager.java:64)
        at nl.rutgerkok.pokkit.plugin.BukkitEventManager.callEvent(BukkitEventManager.java:49)
        at nl.rutgerkok.pokkit.plugin.PokkitPluginManager.callEvent(PokkitPluginManager.java:79)
        at nl.rutgerkok.pokkit.pluginservice.EventTranslator.callCancellable(EventTranslator.java:19)
        at nl.rutgerkok.pokkit.pluginservice.PlayerBlockEvents.onBlockBreak(PlayerBlockEvents.java:59)
        at sun.reflect.GeneratedMethodAccessor69.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29)
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56)
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:553)
        at cn.nukkit.level.Level.useBreakOn(Level.java:1731)
        at cn.nukkit.Player.handleDataPacket(Player.java:2649)
        at cn.nukkit.network.Network.processPackets(Network.java:185)
        at cn.nukkit.network.Network.processBatch(Network.java:156)
        at cn.nukkit.Player.handleDataPacket(Player.java:1912)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:156)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:67)
        at cn.nukkit.network.Network.processInterfaces(Network.java:76)
        at cn.nukkit.Server.tick(Server.java:988)
        at cn.nukkit.Server.tickProcessor(Server.java:791)
        at cn.nukkit.Server.start(Server.java:770)
        at cn.nukkit.Server.<init>(Server.java:455)
        at cn.nukkit.Nukkit.main(Nukkit.java:64)
Caused by: java.lang.UnsupportedOperationException: This method is not supported yet by Pokkit 0.5-SNAPSHOT
        at nl.rutgerkok.pokkit.Pokkit.unsupported(Pokkit.java:81)
        at nl.rutgerkok.pokkit.player.PokkitPlayer.playEffect(PokkitPlayer.java:833)
        at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.playDenyEffect(EventAbstractionListener.java:991)
        at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onBlockBreak(EventAbstractionListener.java:127)
        at sun.reflect.GeneratedMethodAccessor71.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
        ... 26 more

**Comment by NycuRO** [comment]
Protection work, but spam this error if i'm break one block.

**Comment by MrPowerGamerBR** [comment]
Can confirm, I think I can remove that Unsupported code because it is just "fluff".
