### ISSUE TITLE
LaggClear KillMobs error Again

### ISSUE THREAD

**Issue by NycuRO** [rutgerkok/Pokkit#66]
Error: 23:15:48 [ALERT] java.lang.UnsupportedOperationException: This method is not supported yet by Pokkit 0.5-SNAPSHOT
        at nl.rutgerkok.pokkit.Pokkit.unsupported(Pokkit.java:81)
        at nl.rutgerkok.pokkit.entity.PokkitEntity.remove(PokkitEntity.java:373)
        at me.minebuilders.clearlag.Util.removeEntitys(Util.java:89)
        at me.minebuilders.clearlag.managers.EntityManager.removeEntities(EntityManager.java:35)
        at me.minebuilders.clearlag.managers.EntityManager.removeEntities(EntityManager.java:23)
        at me.minebuilders.clearlag.commands.KillmobsCmd.run(KillmobsCmd.java:26)
        at me.minebuilders.clearlag.modules.CommandModule.processCmd(CommandModule.java:35)
        at me.minebuilders.clearlag.CommandListener.onCommand(CommandListener.java:40)
        at nl.rutgerkok.pokkit.plugin.PokkitPlugin.onCommand(PokkitPlugin.java:281)
        at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:244)
        at cn.nukkit.Server.dispatchCommand(Server.java:635)
        at cn.nukkit.command.CommandReader$1.run(CommandReader.java:78)
        at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99)
        at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:282)
        at cn.nukkit.Server.tick(Server.java:996)
        at cn.nukkit.Server.tickProcessor(Server.java:791)
        at cn.nukkit.Server.start(Server.java:770)
        at cn.nukkit.Server.<init>(Server.java:455)
        at cn.nukkit.Nukkit.main(Nukkit.java:64)

**Comment by Langsdorf** [comment]
Solved? I didn't test with LaggClear
