### ISSUE TITLE
WorldGuard EntityDamageByEntityEvent ERROR Spam if Damage Animals.

### ISSUE THREAD

**Issue by NycuRO** [rutgerkok/Pokkit#67]
23:30:17 [ERROR] [Pokkit] Could not pass event EntityDamageByEntityEvent to WorldGuard v6.1.3-SNAPSHOT;c904242
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at nl.rutgerkok.pokkit.plugin.BukkitEventManager.fireEvent(BukkitEventManager.java:64)
        at nl.rutgerkok.pokkit.plugin.BukkitEventManager.callEvent(BukkitEventManager.java:49)
        at nl.rutgerkok.pokkit.plugin.PokkitPluginManager.callEvent(PokkitPluginManager.java:79)
        at nl.rutgerkok.pokkit.pluginservice.EventTranslator.callCancellable(EventTranslator.java:19)
        at nl.rutgerkok.pokkit.pluginservice.EntityEvents.onEntityDamageByEntity(EntityEvents.java:104)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29)
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56)
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:553)
        at cn.nukkit.entity.Entity.attack(Entity.java:795)
        at cn.nukkit.entity.EntityLiving.attack(EntityLiving.java:107)
        at cn.nukkit.entity.EntityHumanType.attack(EntityHumanType.java:150)
        at cn.nukkit.Player.attack(Player.java:4103)
        at creeperCZ.mobplugin.entities.monster.walking.Zombie.attackEntity(Zombie.java:124)
        at creeperCZ.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:167)
        at cn.nukkit.level.Level.doTick(Level.java:765)
        at cn.nukkit.Server.checkTickUpdates(Server.java:924)
        at cn.nukkit.Server.tick(Server.java:999)
        at cn.nukkit.Server.tickProcessor(Server.java:791)
        at cn.nukkit.Server.start(Server.java:770)
        at cn.nukkit.Server.<init>(Server.java:455)
        at cn.nukkit.Nukkit.main(Nukkit.java:64)
Caused by: java.lang.UnsupportedOperationException: This method is not supported yet by Pokkit 0.5-SNAPSHOT
        at nl.rutgerkok.pokkit.Pokkit.unsupported(Pokkit.java:81)
        at nl.rutgerkok.pokkit.entity.PokkitEntity.getMetadata(PokkitEntity.java:141)
        at com.sk89q.worldguard.bukkit.internal.WGMetadata.getIfPresent(WGMetadata.java:64)
        at com.sk89q.worldguard.bukkit.cause.Cause$Builder.addAll(Cause.java:266)
        at com.sk89q.worldguard.bukkit.cause.Cause$Builder.access$100(Cause.java:230)
        at com.sk89q.worldguard.bukkit.cause.Cause.create(Cause.java:191)
        at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onEntityDamage(EventAbstractionListener.java:702)
        at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)

**Comment by MrPowerGamerBR** [comment]
Trying to fix this...
