### ISSUE TITLE
Essentials: /sun, /weather, /day, /night

### ISSUE THREAD

**Issue by NycuRO** [rutgerkok/Pokkit#68]
This command works, please add silence unsuported for not spam console error @MrPowerGamerBR

**Comment by MrPowerGamerBR** [comment]
@NycuRO can you share the error stack trace (enable debug in Essentials config file and run the command)? The stack trace shows the method that is throwing the exception.

**Comment by NycuRO** [comment]
Sun:

> sun world sun
19:23:01 [INFO] [DonateInfo] ServerCommandEvent is called!
19:23:01 [INFO] [Pokkit] {0} issued server command: /{1} {2}
19:23:01 [INFO] Error: This method is not supported yet by Pokkit 0.5-SNAPSHOT
19:23:01 [INFO] [Pokkit] Error calling the command /sun
java.lang.UnsupportedOperationException: This method is not supported yet by Pokkit 0.5-SNAPSHOT
        at nl.rutgerkok.pokkit.Pokkit.unsupported(Pokkit.java:81)
        at nl.rutgerkok.pokkit.world.PokkitWorld.setStorm(PokkitWorld.java:727)
        at com.earth2me.essentials.commands.Commandweather.run(Commandweather.java:86)
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:192)
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:522)
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:401)
        at nl.rutgerkok.pokkit.plugin.PokkitPlugin.onCommand(PokkitPlugin.java:281)
        at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:225)
        at cn.nukkit.Server.dispatchCommand(Server.java:644)
        at cn.nukkit.command.CommandReader$1.run(CommandReader.java:78)
        at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99)
        at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:282)
        at cn.nukkit.Server.tick(Server.java:1005)
        at cn.nukkit.Server.tickProcessor(Server.java:800)
        at cn.nukkit.Server.start(Server.java:779)
        at cn.nukkit.Server.<init>(Server.java:464)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)

**Comment by NycuRO** [comment]
Sun storm:

> sun world storm
19:23:47 [INFO] [DonateInfo] ServerCommandEvent is called!
19:23:47 [INFO] [Pokkit] {0} issued server command: /{1} {2}
19:23:47 [INFO] Error: This method is not supported yet by Pokkit 0.5-SNAPSHOT
19:23:47 [INFO] [Pokkit] Error calling the command /sun
java.lang.UnsupportedOperationException: This method is not supported yet by Pokkit 0.5-SNAPSHOT
        at nl.rutgerkok.pokkit.Pokkit.unsupported(Pokkit.java:81)
        at nl.rutgerkok.pokkit.world.PokkitWorld.setStorm(PokkitWorld.java:727)
        at com.earth2me.essentials.commands.Commandweather.run(Commandweather.java:86)
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:192)
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:522)
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:401)
        at nl.rutgerkok.pokkit.plugin.PokkitPlugin.onCommand(PokkitPlugin.java:281)
        at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:225)
        at cn.nukkit.Server.dispatchCommand(Server.java:644)
        at cn.nukkit.command.CommandReader$1.run(CommandReader.java:78)
        at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99)
        at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:282)
        at cn.nukkit.Server.tick(Server.java:1005)
        at cn.nukkit.Server.tickProcessor(Server.java:800)
        at cn.nukkit.Server.start(Server.java:779)
        at cn.nukkit.Server.<init>(Server.java:464)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)

**Comment by NycuRO** [comment]
day:

> day
19:24:17 [INFO] [DonateInfo] ServerCommandEvent is called!
19:24:17 [INFO] [Pokkit] {0} issued server command: /{1} {2}
19:24:17 [INFO] Error: This method is not supported yet by Pokkit 0.5-SNAPSHOT
19:24:17 [INFO] [Pokkit] Error calling the command /day
java.lang.UnsupportedOperationException: This method is not supported yet by Pokkit 0.5-SNAPSHOT
        at nl.rutgerkok.pokkit.Pokkit.unsupported(Pokkit.java:81)
        at nl.rutgerkok.pokkit.world.PokkitWorld.getTime(PokkitWorld.java:464)
        at com.earth2me.essentials.commands.Commandtime.setWorldsTime(Commandtime.java:113)
        at com.earth2me.essentials.commands.Commandtime.run(Commandtime.java:84)
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:192)
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:522)
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:401)
        at nl.rutgerkok.pokkit.plugin.PokkitPlugin.onCommand(PokkitPlugin.java:281)
        at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:225)
        at cn.nukkit.Server.dispatchCommand(Server.java:644)
        at cn.nukkit.command.CommandReader$1.run(CommandReader.java:78)
        at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99)
        at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:282)
        at cn.nukkit.Server.tick(Server.java:1005)
        at cn.nukkit.Server.tickProcessor(Server.java:800)
        at cn.nukkit.Server.start(Server.java:779)
        at cn.nukkit.Server.<init>(Server.java:464)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)

**Comment by NycuRO** [comment]
Night:

> night
19:24:31 [INFO] [DonateInfo] ServerCommandEvent is called!
19:24:31 [INFO] [Pokkit] {0} issued server command: /{1} {2}
19:24:31 [INFO] Error: This method is not supported yet by Pokkit 0.5-SNAPSHOT
19:24:31 [INFO] [Pokkit] Error calling the command /night
java.lang.UnsupportedOperationException: This method is not supported yet by Pokkit 0.5-SNAPSHOT
        at nl.rutgerkok.pokkit.Pokkit.unsupported(Pokkit.java:81)
        at nl.rutgerkok.pokkit.world.PokkitWorld.getTime(PokkitWorld.java:464)
        at com.earth2me.essentials.commands.Commandtime.setWorldsTime(Commandtime.java:113)
        at com.earth2me.essentials.commands.Commandtime.run(Commandtime.java:84)
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:192)
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:522)
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:401)
        at nl.rutgerkok.pokkit.plugin.PokkitPlugin.onCommand(PokkitPlugin.java:281)
        at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:225)
        at cn.nukkit.Server.dispatchCommand(Server.java:644)
        at cn.nukkit.command.CommandReader$1.run(CommandReader.java:78)
        at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99)
        at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:282)
        at cn.nukkit.Server.tick(Server.java:1005)
        at cn.nukkit.Server.tickProcessor(Server.java:800)
        at cn.nukkit.Server.start(Server.java:779)
        at cn.nukkit.Server.<init>(Server.java:464)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)
