### ISSUE TITLE
Player Chat Event is broken?

### ISSUE THREAD

**Issue by PikyCZ** [rutgerkok/Pokkit#71]
2017-2-25 19:20:19 [INFO] [Hrac]PikyCZ: c
2017-2-25 19:21:21 [INFO] [Multipass] Group Majitel is contains unknown subgroup OPMajitel. Please check group configuration
2017-2-25 19:21:22 [CRITICAL] "Could not pass event 'cn.nukkit.event.player.PlayerChatEvent' to 'Pokkit v0.5-SNAPSHOT': null on nl.rutgerkok.pokkit.pluginservice.PlayerChatEvents
2017-2-25 19:21:22 [ALERT] cn.nukkit.utils.EventException
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34)
	at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56)
	at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:553)
	at cn.nukkit.Player.handleDataPacket(Player.java:2976)
	at cn.nukkit.network.Network.processPackets(Network.java:185)
	at cn.nukkit.network.Network.processBatch(Network.java:156)
	at cn.nukkit.Player.handleDataPacket(Player.java:1906)
	at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:155)
	at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
	at cn.nukkit.network.Network.processInterfaces(Network.java:76)
	at cn.nukkit.Server.tick(Server.java:997)
	at cn.nukkit.Server.tickProcessor(Server.java:800)
	at cn.nukkit.Server.start(Server.java:779)
	at cn.nukkit.Server.<init>(Server.java:464)
	at cn.nukkit.Nukkit.main(Nukkit.java:68)
Caused by: java.util.UnknownFormatConversionException: Conversion = '1'
	at org.bukkit.event.player.AsyncPlayerChatEvent.setFormat(AsyncPlayerChatEvent.java:100)
	at nl.rutgerkok.pokkit.pluginservice.PlayerChatEvents.onPlayerChat(PlayerChatEvents.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29)
	... 15 more

**Comment by Langsdorf** [comment]
What chat plugin you are using?

**Comment by PikyCZ** [comment]
MultiChat .. https://forums.nukkit.io/resources/multichat.104/

**Comment by PikyCZ** [comment]
in Pokkit 5.0 is ok .. .)

**Comment by PikyCZ** [comment]
how to disable this event?

**Comment by PikyCZ** [comment]
This problem spamming console..

**Comment by PikyCZ** [comment]
@Langsdorf  can you fix it?

**Comment by Langsdorf** [comment]
PlayerChatEvent seems normal to me

**Comment by rutgerkok** [comment]
The error was that the `format` parameter works differently in Bukkit and in Nukkit. I have added some code to translate between the two.
