### ISSUE TITLE
CombatLog error

### ISSUE THREAD

**Issue by SuperAlecs** [rutgerkok/Pokkit#74]
When player hit another player the console says this

```
2017-3-11 13:13:08 [ERROR] [Pokkit] Could not pass event EntityDamageByEntityEvent to CombatLog v1.8.11
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	at nl.rutgerkok.pokkit.plugin.BukkitEventManager.fireEvent(BukkitEventManager.java:64)
	at nl.rutgerkok.pokkit.plugin.BukkitEventManager.callEvent(BukkitEventManager.java:49)
	at nl.rutgerkok.pokkit.plugin.PokkitPluginManager.callEvent(PokkitPluginManager.java:79)
	at nl.rutgerkok.pokkit.pluginservice.EventTranslator.callCancellable(EventTranslator.java:19)
	at nl.rutgerkok.pokkit.pluginservice.EntityEvents.onEntityDamageByEntity(EntityEvents.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29)
	at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56)
	at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:553)
	at cn.nukkit.entity.Entity.attack(Entity.java:775)
	at cn.nukkit.entity.EntityLiving.attack(EntityLiving.java:107)
	at cn.nukkit.entity.EntityHumanType.attack(EntityHumanType.java:150)
	at cn.nukkit.Player.attack(Player.java:4143)
	at cn.nukkit.Player.handleDataPacket(Player.java:2748)
	at cn.nukkit.network.Network.processPackets(Network.java:185)
	at cn.nukkit.network.Network.processBatch(Network.java:156)
	at cn.nukkit.Player.handleDataPacket(Player.java:1929)
	at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:155)
	at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
	at cn.nukkit.network.Network.processInterfaces(Network.java:76)
	at cn.nukkit.Server.tick(Server.java:1001)
	at cn.nukkit.Server.tickProcessor(Server.java:803)
	at cn.nukkit.Server.start(Server.java:782)
	at cn.nukkit.Server.<init>(Server.java:467)
	at cn.nukkit.Nukkit.main(Nukkit.java:68)
Caused by: java.lang.NoSuchMethodError: com.massivecraft.factions.FLocation.<init>(Lorg/bukkit/Location;)V
	at com.jackproehl.plugins.listeners.EntityDamageByEntityListener.tagAttacker(EntityDamageByEntityListener.java:121)
	at com.jackproehl.plugins.listeners.EntityDamageByEntityListener.onEntityDamageByEntity(EntityDamageByEntityListener.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
	... 30 more
```

**Comment by rutgerkok** [comment]
Seems like another plugin is missing, or cannot be loaded:

`com.massivecraft.factions.FLocation` is missing

**Comment by NycuRO** [comment]
Please install Massive Factions and try again.

But @rutgerkok ,it's not single problem.

**Comment by SuperAlecs** [comment]
Ok now it works, but in Pokkit it isn't PlayerCommandPreprocessEvent, so blocked commands doesn't work,
@rutgerkok can you add this event?

**Comment by rutgerkok** [comment]
Depends. Has Nukkit an equivalent event?

**Comment by Langsdorf** [comment]
@rutgerkok Yes, https://github.com/Nukkit/Nukkit/blob/master/src/main/java/cn/nukkit/event/player/PlayerCommandPreprocessEvent.java

**Comment by imjack** [comment]
It's depending on a version on factions hence it crashing.
