### ISSUE TITLE
Random spawn support

### ISSUE THREAD

**Issue by twixi** [rutgerkok/Pokkit#78]
https://dev.bukkit.org/projects/random-spawn?gameCategorySlug=bukkit-plugins&projectID=31459

https://github.com/Josvth/Random-Spawn
please create support this plugin!

**Comment by rutgerkok** [comment]
I need a more specific error. What exactly is not working?

(I'm closing this issue for now, but I can always reopen it if needed. You can also still comment while it's closed.)

**Comment by twixi** [comment]
`2017-4-3 20:40:58 [ERROR] Could not load 'RandomSpawn-2.6.jar' in folder 'D:\Nukkit\plugins': java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.String
	at cn.nukkit.plugin.PluginDescription.loadMap(PluginDescription.java:146)
	at cn.nukkit.plugin.PluginDescription.<init>(PluginDescription.java:137)
	at cn.nukkit.plugin.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:92)
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:165)
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:132)
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:124)
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:120)
	at cn.nukkit.Server.<init>(Server.java:395)
	at cn.nukkit.Nukkit.main(Nukkit.java:68)

2017-4-3 20:40:58 [ALERT] java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.String
	at cn.nukkit.plugin.PluginDescription.loadMap(PluginDescription.java:146)
	at cn.nukkit.plugin.PluginDescription.<init>(PluginDescription.java:137)
	at cn.nukkit.plugin.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:92)
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:165)
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:132)
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:124)
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:120)
	at cn.nukkit.Server.<init>(Server.java:395)
	at cn.nukkit.Nukkit.main(Nukkit.java:68)
`
https://dev.bukkit.org/projects/random-spawn/files/696056

**Comment by rutgerkok** [comment]
This the offending source code:

```
    this.plugin.getCommand("randomspawn").setExecutor(this);
    this.plugin.getCommand("rs").setExecutor(this); // error occured on this line
```

So the error is that `plugin.getCommand(...)` does not work on aliases. Thanks, that should be enough info for fixing it!

**Comment by twixi** [comment]
You can make this plugin to work?

**Comment by rutgerkok** [comment]
I probably can if I put enough time in it, however, please see this section of the README:

> In general, I will only fix a bug for you if happens to also affect me. Pokkit is a personal project that I uploaded in the hope that it will be useful to others, but I'm not willing to spend the time to create a complete, bug-free implementation of the Spigot API. See my reasoning in the introduction.

> Still, I will leave open all valid bug reports, so that anyone interested in improving Pokkit can have a look.
