### ISSUE TITLE
NullPointerException in PokkitBlockState.getBlockState

### ISSUE THREAD

**Issue by SuperAlecs** [rutgerkok/Pokkit#79]
In the new Pokkit version the console spam this message:

```
2017-4-2 18:29:24 [CRITICAL] Could not pass event 'cn.nukkit.event.block.BlockSpreadEvent' to 'Pokkit v0.6-SNAPSHOT': null on nl.rutgerkok.pokkit.pluginservice.PlayerBlockEvents
2017-4-2 18:29:24 [ALERT] cn.nukkit.utils.EventException
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34)
	at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56)
	at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:553)
	at cn.nukkit.block.BlockGrass.onUpdate(BlockGrass.java:82)
	at cn.nukkit.level.Level.tickChunks(Level.java:1074)
	at cn.nukkit.level.Level.doTick(Level.java:781)
	at cn.nukkit.Server.checkTickUpdates(Server.java:946)
	at cn.nukkit.Server.tick(Server.java:1021)
	at cn.nukkit.Server.tickProcessor(Server.java:808)
	at cn.nukkit.Server.start(Server.java:787)
	at cn.nukkit.Server.<init>(Server.java:472)
	at cn.nukkit.Nukkit.main(Nukkit.java:68)
Caused by: java.lang.NullPointerException
	at nl.rutgerkok.pokkit.blockstate.PokkitBlockState.getBlockState(PokkitBlockState.java:35)
	at nl.rutgerkok.pokkit.pluginservice.PlayerBlockEvents.onBlockSpread(PlayerBlockEvents.java:182)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29)
	... 11 more
```

**Comment by rutgerkok** [comment]
It won't solve the problem, but could you test this file?

https://www.dropbox.com/s/sawhnca6kqn7og0/Pokkit.jar?dl=0

It displays some more information on where exactly the error occurs.

**Comment by SuperAlecs** [comment]
I tested your file but the message is the same

**Comment by rutgerkok** [comment]
Could you still post it? I hope that at least something minor, like the numbers, is different.
