### ISSUE TITLE
ItemMeta.getLore() returns empty list instead of null

### ISSUE THREAD

**Issue by PikyCZ** [rutgerkok/Pokkit#86]
[ERROR] [Pokkit] Could not pass event PlayerInteractEvent to PlayerHousing v1.0 
org.bukkit.event.EventException 
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) 
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) 
at nl.rutgerkok.pokkit.plugin.BukkitEventManager.fireEvent(BukkitEventManager.java:64) 
at nl.rutgerkok.pokkit.plugin.BukkitEventManager.callEvent(BukkitEventManager.java:49) 
at nl.rutgerkok.pokkit.plugin.PokkitPluginManager.callEvent(PokkitPluginManager.java:79) 
at nl.rutgerkok.pokkit.pluginservice.EventTranslator.callCancellable(EventTranslator.java:30) 
at nl.rutgerkok.pokkit.pluginservice.PlayerInteractEvents.onPlayerInteract(PlayerInteractEvents.java:59) 
at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source) 
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
at java.lang.reflect.Method.invoke(Method.java:498) 
at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) 
at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) 
at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:553) 
at cn.nukkit.level.Level.useItemOn(Level.java:1859) 
at cn.nukkit.Player.handleDataPacket(Player.java:2182) 
at cn.nukkit.network.Network.processPackets(Network.java:180) 
at cn.nukkit.network.Network.processBatch(Network.java:156) 
at cn.nukkit.Player.handleDataPacket(Player.java:1893) 
at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:155) 
at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123) 
at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66) 
at cn.nukkit.network.Network.processInterfaces(Network.java:76) 
at cn.nukkit.Server.tick(Server.java:1011) 
at cn.nukkit.Server.tickProcessor(Server.java:809) 
at cn.nukkit.Server.start(Server.java:788) 
at cn.nukkit.Server.(Server.java:473) 
at cn.nukkit.Nukkit.main(Nukkit.java:68) 
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0 
at java.util.ArrayList.rangeCheck(ArrayList.java:653) 
at java.util.ArrayList.get(ArrayList.java:429) 
at ghg.plugin.player.housing.GriefProtection.onPlayerRightClickBlock(GriefProtection.java:47) 
at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source) 
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
at java.lang.reflect.Method.invoke(Method.java:498) 
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) 
... 26 more 

https://www.spigotmc.org/resources/playerhousing.38299/

**Comment by rutgerkok** [comment]
Thanks, should be fixed now.

**Comment by PikyCZ** [comment]
can you make working ??

![2017-04-06 1](https://cloud.githubusercontent.com/assets/19613582/24755357/315f8f70-1ada-11e7-9be3-b1c400245890.png)

![2017-04-06 2](https://cloud.githubusercontent.com/assets/19613582/24755369/39834570-1ada-11e7-8064-83852e2e26d4.png)

**Comment by rutgerkok** [comment]
The plugin probably requires lores to be implemented properly. I'll create a separate issue for that.

**Comment by PikyCZ** [comment]
i mean interact with item?

**Comment by rutgerkok** [comment]
This plugin, as far as I can see, stores necessary information in the lore. Without lore support, it won't function.

**Comment by PikyCZ** [comment]
ok :)
