### ISSUE TITLE
Void Spawn issue

### ISSUE THREAD

**Issue by PikyCZ** [rutgerkok/Pokkit#88]
[ERROR] [Pokkit] Could not pass event PlayerMoveEvent to VoidSpawn v1.14.0 
org.bukkit.event.EventException 
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) 
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) 
at nl.rutgerkok.pokkit.plugin.BukkitEventManager.fireEvent(BukkitEventManager.java:64) 
at nl.rutgerkok.pokkit.plugin.BukkitEventManager.callEvent(BukkitEventManager.java:49) 
at nl.rutgerkok.pokkit.plugin.PokkitPluginManager.callEvent(PokkitPluginManager.java:79) 
at nl.rutgerkok.pokkit.pluginservice.EventTranslator.callCancellable(EventTranslator.java:30) 
at nl.rutgerkok.pokkit.pluginservice.PlayerInteractEvents.onMove(PlayerInteractEvents.java:34) 
at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source) 
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
at java.lang.reflect.Method.invoke(Method.java:498) 
at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) 
at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) 
at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:553) 
at cn.nukkit.Player.processMovement(Player.java:1441) 
at cn.nukkit.Player.onUpdate(Player.java:1572) 
at cn.nukkit.level.Level.doTick(Level.java:761) 
at cn.nukkit.Server.checkTickUpdates(Server.java:948) 
at cn.nukkit.Server.tick(Server.java:1023) 
at cn.nukkit.Server.tickProcessor(Server.java:810) 
at cn.nukkit.Server.start(Server.java:789) 
at cn.nukkit.Server.(Server.java:474) 
at cn.nukkit.Nukkit.main(Nukkit.java:68) 
Caused by: java.lang.NullPointerException 
at com.endercrest.voidspawn.MoveListener.onMoveEvent(MoveListener.java:18) 
at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source) 
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
at java.lang.reflect.Method.invoke(Method.java:498) 
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) 
... 21 more

**Comment by rutgerkok** [comment]
The error occurs somewhere on this line:

```
if (player.getLocation().getBlock().getRelative(BlockFace.DOWN).getType().isSolid()) {
```

Unfortunately, this is a whole chain of instructions (get location, get block, get block blow, get type, is solid). In any of those, something can go wrong. Therefore, this bug report is not that useful: potential contributors cannot see where they need to start fixing this. So I'm closing this bug report, as it is unlikely to be fixed.
