### ISSUE TITLE
Could not pass event 'cn.nukkit.event.block.BlockSpreadEvent

### ISSUE THREAD

**Issue by twixi** [rutgerkok/Pokkit#89]
Pokkit 0.5
`[CRITICAL] Could not pass event 'cn.nukkit.event.block.BlockSpreadEvent' to 'Pokkit v0.5': null on nl.rutgerkok.pokkit.pluginservice.PlayerBlockEvents
[ALERT] cn.nukkit.utils.EventException
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34)
	at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56)
	at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:553)
	at cn.nukkit.block.BlockGrass.onUpdate(BlockGrass.java:82)
	at cn.nukkit.level.Level.tickChunks(Level.java:1074)
	at cn.nukkit.level.Level.doTick(Level.java:781)
	at cn.nukkit.Server.checkTickUpdates(Server.java:945)
	at cn.nukkit.Server.tick(Server.java:1020)
	at cn.nukkit.Server.tickProcessor(Server.java:807)
	at cn.nukkit.Server.start(Server.java:786)
	at cn.nukkit.Server.<init>(Server.java:471)
	at cn.nukkit.Nukkit.main(Nukkit.java:68)
Caused by: java.lang.NullPointerException
	at nl.rutgerkok.pokkit.blockstate.PokkitBlockState.getBlockState(PokkitBlockState.java:35)
	at nl.rutgerkok.pokkit.pluginservice.PlayerBlockEvents.onBlockSpread(PlayerBlockEvents.java:182)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29)
	... 11 more`

**Comment by RaynLegends** [comment]
This has been fixed in the latest commit, could you try to compile it and see if you still get the exception?

**Comment by RaynLegends** [comment]
I'm closing since you haven't commented in more than a month and, as far as I know, this got fixed.
