### ISSUE TITLE
Other Permission Error Plugin

### ISSUE THREAD

**Issue by NycuRO** [rutgerkok/Pokkit#99]
01:50:37 [CRITICAL] Exception while invoking run
java.lang.UnsupportedOperationException: Don't know how to convert class me.lucko.luckperms.bukkit.model.DummyPermissible
        at nl.rutgerkok.pokkit.permission.PokkitPermissible.toNukkit(PokkitPermissible.java:27)
        at nl.rutgerkok.pokkit.plugin.PokkitPluginManager.unsubscribeFromDefaultPerms(PokkitPluginManager.java:274)
        at me.lucko.luckperms.bukkit.model.DefaultsProvider.unregisterDefaults(DefaultsProvider.java:97)
        at me.lucko.luckperms.bukkit.model.DefaultsProvider.refreshOp(DefaultsProvider.java:57)
        at me.lucko.luckperms.bukkit.model.DefaultsProvider.refresh(DefaultsProvider.java:52)
        at me.lucko.luckperms.bukkit.LPBukkitPlugin.lambda$enable$2(LPBukkitPlugin.java:182)
        at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99)
        at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:283)
        at cn.nukkit.Server.tick(Server.java:1004)
        at cn.nukkit.Server.tickProcessor(Server.java:794)
        at cn.nukkit.Server.start(Server.java:773)
        at cn.nukkit.Server.<init>(Server.java:464)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)

**Comment by NycuRO** [comment]
> java.lang.ClassNotFoundException: net.glowstone.entity.GlowHumanEntity
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at me.lucko.luckperms.bukkit.model.Injector.<clinit>(Injector.java:62)
        at me.lucko.luckperms.bukkit.BukkitListener.onPlayerQuit(BukkitListener.java:221)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at nl.rutgerkok.pokkit.plugin.BukkitEventManager.fireEvent(BukkitEventManager.java:64)
        at nl.rutgerkok.pokkit.plugin.BukkitEventManager.callEvent(BukkitEventManager.java:49)
        at nl.rutgerkok.pokkit.plugin.PokkitPluginManager.callEvent(PokkitPluginManager.java:79)
        at nl.rutgerkok.pokkit.pluginservice.EventTranslator.callUncancellable(EventTranslator.java:41)
        at nl.rutgerkok.pokkit.pluginservice.PlayerConnectEvents.onPlayerQuit(PlayerConnectEvents.java:67)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29)
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56)
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:553)
        at cn.nukkit.Player.close(Player.java:3958)
        at cn.nukkit.Player.close(Player.java:3944)
        at cn.nukkit.Player.processLogin(Player.java:1883)
        at cn.nukkit.Player.handleDataPacket(Player.java:2121)
        at a.e.b.handleDataPacket(NukkitPlayer.java:57)
        at cn.nukkit.network.Network.processPackets(Network.java:180)
        at cn.nukkit.network.Network.processBatch(Network.java:151)
        at cn.nukkit.Player.handleDataPacket(Player.java:1992)
        at a.e.b.handleDataPacket(NukkitPlayer.java:57)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
        at cn.nukkit.network.Network.processInterfaces(Network.java:75)
        at cn.nukkit.Server.tick(Server.java:996)
        at cn.nukkit.Server.tickProcessor(Server.java:794)
        at cn.nukkit.Server.start(Server.java:773)
        at cn.nukkit.Server.<init>(Server.java:464)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)
java.lang.ClassNotFoundException: net.glowstone.entity.GlowHumanEntity
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at me.lucko.luckperms.bukkit.model.Injector.<clinit>(Injector.java:62)
        at me.lucko.luckperms.bukkit.BukkitListener.onPlayerQuit(BukkitListener.java:221)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at nl.rutgerkok.pokkit.plugin.BukkitEventManager.fireEvent(BukkitEventManager.java:64)
        at nl.rutgerkok.pokkit.plugin.BukkitEventManager.callEvent(BukkitEventManager.java:49)
        at nl.rutgerkok.pokkit.plugin.PokkitPluginManager.callEvent(PokkitPluginManager.java:79)
        at nl.rutgerkok.pokkit.pluginservice.EventTranslator.callUncancellable(EventTranslator.java:41)
        at nl.rutgerkok.pokkit.pluginservice.PlayerConnectEvents.onPlayerQuit(PlayerConnectEvents.java:67)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29)
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56)
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:553)
        at cn.nukkit.Player.close(Player.java:3958)
        at cn.nukkit.Player.close(Player.java:3944)
        at cn.nukkit.Player.processLogin(Player.java:1883)
        at cn.nukkit.Player.handleDataPacket(Player.java:2121)
        at a.e.b.handleDataPacket(NukkitPlayer.java:57)
        at cn.nukkit.network.Network.processPackets(Network.java:180)
        at cn.nukkit.network.Network.processBatch(Network.java:151)
        at cn.nukkit.Player.handleDataPacket(Player.java:1992)
        at a.e.b.handleDataPacket(NukkitPlayer.java:57)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
        at cn.nukkit.network.Network.processInterfaces(Network.java:75)
        at cn.nukkit.Server.tick(Server.java:996)
        at cn.nukkit.Server.tickProcessor(Server.java:794)
        at cn.nukkit.Server.start(Server.java:773)
        at cn.nukkit.Server.<init>(Server.java:464)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)

**Comment by NycuRO** [comment]
01:52:26 [ERROR] [Pokkit] Error occurred while disabling LuckPerms v3.2.20 (Is it up to date?)
java.lang.UnsupportedOperationException: Don't know how to convert class me.lucko.luckperms.bukkit.model.DummyPermissible
        at nl.rutgerkok.pokkit.permission.PokkitPermissible.toNukkit(PokkitPermissible.java:27)
        at nl.rutgerkok.pokkit.plugin.PokkitPluginManager.unsubscribeFromDefaultPerms(PokkitPluginManager.java:274)
        at me.lucko.luckperms.bukkit.model.DefaultsProvider.unregisterDefaults(DefaultsProvider.java:97)
        at me.lucko.luckperms.bukkit.model.DefaultsProvider.close(DefaultsProvider.java:75)
        at me.lucko.luckperms.bukkit.LPBukkitPlugin.onDisable(LPBukkitPlugin.java:362)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273)
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361)
        at nl.rutgerkok.pokkit.plugin.PokkitPluginLoader.disablePlugin(PokkitPluginLoader.java:64)
        at cn.nukkit.plugin.PluginManager.disablePlugin(PluginManager.java:520)
        at cn.nukkit.plugin.PluginManager.disablePlugins(PluginManager.java:513)
        at cn.nukkit.Server.forceShutdown(Server.java:719)
        at cn.nukkit.Server.start(Server.java:774)
        at cn.nukkit.Server.<init>(Server.java:464)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)

**Comment by NycuRO** [comment]
01:54:34 [ERROR] [Pokkit] Error occurred while enabling bPermissions v2.10.9 (Is it up to date?)
java.lang.NullPointerException
        at de.bananaco.bpermissions.imp.Permissions.onEnable(Permissions.java:60)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
        at nl.rutgerkok.pokkit.plugin.PokkitPluginLoader.enablePlugin(PokkitPluginLoader.java:69)
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:446)
        at nl.rutgerkok.pokkit.plugin.PokkitPluginManager.enablePlugin(PokkitPluginManager.java:107)
        at nl.rutgerkok.pokkit.pluginservice.PluginService.enablePlugins(PluginService.java:22)
        at nl.rutgerkok.pokkit.pluginservice.PluginService.onEnable(PluginService.java:29)
        at nl.rutgerkok.pokkit.Pokkit.lambda$onEnable$1(Pokkit.java:113)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at nl.rutgerkok.pokkit.Pokkit.onEnable(Pokkit.java:113)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at nl.rutgerkok.pokkit.startup.NukkitHook.onEnable(NukkitHook.java:26)
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89)
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:113)
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:446)
        at cn.nukkit.Server.enablePlugin(Server.java:620)
        at cn.nukkit.Server.enablePlugins(Server.java:609)
        at cn.nukkit.Server.<init>(Server.java:462)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)
